# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/roadMap/ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 738)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.canvas.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.canvas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.canvas.setObjectName("canvas")
        self.horizontalLayout.addWidget(self.canvas)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 200, 606))
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 200, 606))
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toolBox.addItem(self.page_2, "")
        self.horizontalLayout.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.create = QtWidgets.QAction(MainWindow)
        self.create.setObjectName("create")
        self.save = QtWidgets.QAction(MainWindow)
        self.save.setObjectName("save")
        self.load = QtWidgets.QAction(MainWindow)
        self.load.setObjectName("load")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.saveAs = QtWidgets.QAction(MainWindow)
        self.saveAs.setObjectName("saveAs")
        self.menu.addAction(self.create)
        self.menu.addSeparator()
        self.menu.addAction(self.save)
        self.menu.addAction(self.saveAs)
        self.menu.addSeparator()
        self.menu.addAction(self.load)
        self.menu.addSeparator()
        self.menu.addAction(self.exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Items"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Фон"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.create.setText(_translate("MainWindow", "Создать"))
        self.create.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.save.setText(_translate("MainWindow", "Сохранить"))
        self.save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.load.setText(_translate("MainWindow", "Загрузить"))
        self.load.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.saveAs.setText(_translate("MainWindow", "Сохранить как"))
        self.saveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
import resource_rc
