# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sizeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_canvasSize(object):
    def setupUi(self, canvasSize):
        canvasSize.setObjectName("canvasSize")
        canvasSize.resize(300, 150)
        canvasSize.setMinimumSize(QtCore.QSize(300, 150))
        canvasSize.setMaximumSize(QtCore.QSize(300, 150))
        self.gridLayout = QtWidgets.QGridLayout(canvasSize)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(canvasSize)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1)
        self.widthBox = QtWidgets.QSpinBox(canvasSize)
        self.widthBox.setMinimum(512)
        self.widthBox.setMaximum(16777215)
        self.widthBox.setObjectName("widthBox")
        self.gridLayout.addWidget(self.widthBox, 0, 1, 1, 1)
        self.higthBox = QtWidgets.QSpinBox(canvasSize)
        self.higthBox.setMinimum(512)
        self.higthBox.setMaximum(16777215)
        self.higthBox.setSingleStep(1)
        self.higthBox.setObjectName("higthBox")
        self.gridLayout.addWidget(self.higthBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(canvasSize)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(canvasSize)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        self.retranslateUi(canvasSize)
        self.buttonBox.accepted.connect(canvasSize.accept) # type: ignore
        self.buttonBox.rejected.connect(canvasSize.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(canvasSize)

    def retranslateUi(self, canvasSize):
        _translate = QtCore.QCoreApplication.translate
        canvasSize.setWindowTitle(_translate("canvasSize", "Dialog"))
        self.label.setText(_translate("canvasSize", "Ширина"))
        self.label_2.setText(_translate("canvasSize", "Высота"))

    def get_size(self):
        return self.higthBox.value(), self.widthBox.value()